name: Build

on:
  push:
    branches:
      - "master"
      - "inomo"
    tags:
      - "V*"

permissions:
  contents: write

jobs:
  buildlinux:
    name: Linux x64
    runs-on: ubuntu-20.04

    steps:
      - name: Prepare Environment
        run: |
            sudo apt-get install libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-render-util0 libxcb-xinerama0 libxcb-randr0 libxkbcommon-x11-0

      - name: Prepare Qt Libraries
        uses: jurplel/install-qt-action@v3

      - name: Clone
        uses: actions/checkout@v3

      - name: Compile
        run: |
          qmake CONFIG+=release PREFIX=/usr SavvyCAN.pro
          make -j`grep -c ^processor /proc/cpuinfo`
          
      - name: Package     
        run: |
          make INSTALL_ROOT=appdir install
          wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
          chmod a+x linuxdeployqt-continuous-x86_64.AppImage
          ./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/SavvyCAN.desktop -appimage -extra-plugins=iconengines,platformthemes/libqgtk3.so,canbus

      - uses: actions/upload-artifact@v4
        with:
          name: SavvyCAN-Linux_x64.AppImage
          path: SavvyCAN-*x86_64.AppImage
          if-no-files-found: error
      
  buildmacos:
    name: macOS x64
    runs-on: macos-13

    steps:
      - name: Prepare macOS Environment
        run: |
          brew install 'qt@5'
          brew link 'qt@5' --force

      - name: Clone
        uses: actions/checkout@v3

      - name: Compile     
        run: |
          qmake CONFIG+=release CONFIG+=sdk_no_version_check SavvyCAN.pro
          make -j`sysctl kern.aioprocmax | awk '{print $2}'`

      - name: Package     
        run: |
          qt5_dir=$(brew --prefix 'qt@5')
          pcan_usb_version="0.13"
          pcan_usb_url="https://github.com/mac-can/PCBUSB-Library/releases/download/v${pcan_usb_version}/macOS_Library_for_PCANUSB_v${pcan_usb_version}.tar.gz"
          contents_dir="SavvyCAN.app/Contents"

          # copy help
          mkdir -p "$contents_dir/MacOS/help"
          cp -R help/* "$contents_dir/MacOS/help"

          # copy canbus plugins
          mkdir -p "$contents_dir/PlugIns/canbus"
          cp -R "$qt5_dir/plugins/canbus"/* "$contents_dir/PlugIns/canbus"

          # download and bundle PCANUSB library
          temp_dir=$(mktemp -d)
          curl -sSL "$pcan_usb_url" | gtar -C "$temp_dir" -zx --wildcards '*.dylib'
          mkdir -p "$contents_dir/Frameworks"
          mv "$temp_dir/PCBUSB/libPCBUSB.${pcan_usb_version}.dylib" "$contents_dir/Frameworks/libPCBUSB.dylib"

          echo "Prepared files:"
          find SavvyCAN.app | sed 's/^/  /'

          macdeployqt SavvyCAN.app -dmg
      
      - uses: actions/upload-artifact@v4
        with:
          name: SavvyCAN-macOS_x64.dmg
          path: SavvyCAN.dmg
          if-no-files-found: error
          
  buildwindows:
    name: Windows x64
    runs-on: windows-2019

    steps:      
      - name: Prepare Qt Libraries
        uses: jurplel/install-qt-action@v3

      - name: Clone
        uses: actions/checkout@v3
      
      - name: Compile
        shell: cmd
        run: | 
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"

          qmake CONFIG+=release SavvyCAN.pro
          nmake /C

      - name: Package
        run: |
          mkdir package
          copy "release/SavvyCAN.exe" package/
          mkdir package/help
          copy  help/*.md package/help/
          mkdir package/help/images
          copy help/images/*.* package/help/images/
          mkdir package/examples
          copy examples/*.* package/examples/          
          copy "${Env:Qt5_Dir}/bin/Qt5Core.dll" package/
          copy "${Env:Qt5_Dir}/bin/Qt5Gui.dll" package/
          copy "${Env:Qt5_Dir}/bin/Qt5Network.dll" package/
          copy "${Env:Qt5_Dir}/bin/Qt5PrintSupport.dll" package/
          copy "${Env:Qt5_Dir}/bin/Qt5Qml.dll" package/
          copy "${Env:Qt5_Dir}/bin/Qt5SerialBus.dll" package/
          copy "${Env:Qt5_Dir}/bin/Qt5SerialPort.dll" package/
          copy "${Env:Qt5_Dir}/bin/Qt5Widgets.dll" package/
          mkdir package/imageformats
          copy "${Env:Qt5_Dir}/plugins/imageformats/*.*" package/imageformats/
          mkdir package/platforms
          copy "${Env:Qt5_Dir}/plugins/platforms/*.*" package/platforms/
          mkdir package/styles
          copy "${Env:Qt5_Dir}/plugins/styles/*.*" package/styles/
          mkdir package/canbus
          copy "${Env:Qt5_Dir}/plugins/canbus/*.*" package/canbus/

      - uses: actions/upload-artifact@v4
        with:
          name: SavvyCAN-Windows_x64
          path: package
          if-no-files-found: error
 
  pre-release:
    if: startsWith(github.ref, 'refs/tags/')
    name: "pre-release"
    runs-on: "ubuntu-latest"
    needs: [buildwindows, buildmacos, buildlinux]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v4.1.7

      - name: Display structure of downloaded files
        run: zip -r SavvyCAN-Windows_x64_CIBuild.zip SavvyCAN-Windows_x64

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            SavvyCAN-Linux_x64.AppImage/SavvyCAN-*x86_64.AppImage
            SavvyCAN-Windows_x64_CIBuild.zip
            SavvyCAN-macOS_x64.dmg/SavvyCAN.dmg
